### ISSUE TITLE
Artifact of Command Behavior has changed resulting in the mod not working. 

### ISSUE THREAD

**Issue by nickg11** [programit/RoR2InstanceLootPlugin#5]
When running this mod on the new update it seems to be running into some issues. I am not 100% clear on how these mods interact with the game and the mod is not erroring out. From what I can tell it's failing to scan the DLL and hook it so even though it's crashing its not working either. I have attached two different logs, one is the instance mod and it's dependencies only the other is with a full suite of mods installed though I doubt there is any other stacking issues with the extra mods.

To note as I said above the mod is not directly error out and failing, it doesn't even show up as a warning from BepInEx. In game the F3 command to call all items to you does not do anything. No errors in console but also doesn't move the items. The two commands created by the mod drop_rate and drop_rate_report still function.

After discussing with some people on the ROR2 modding discord it seems that the issue is that with the latest update they refactored how the Artifact of Command functions.

Some key lines to note in the log are:

- ScanAllAssemblies failed
```
ScanAllAssemblies failed for 'InstanceLootPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null':  System.TypeLoadException: Could not resolve type with token 01000031 (from typeref, class/assembly orig_OnDropletHitGroundServer, )
```
-  memberInfo.GetCustomAttributes(false) failed for : InstanceLootPlugin.InstanceLootPlugin
```
[Debug  :RoR2BepInExPack] memberInfo.GetCustomAttributes(false) failed for : InstanceLootPlugin.InstanceLootPlugin
CommandArtifactManager_OnDropletHitGroundServer
System.TypeLoadException: Could not resolve type with token 01000031 (from typeref, class/assembly orig_OnDropletHitGroundServer, )
```
- Hook Fails repeatedly
```
[Debug  :InstanceBasedLoot] Force Disabled: Will not hook.
```
- Interesting note is that the same reference is failing in BepInEx so maybe this is a BepInEx or game issue.
```
[Debug  :RoR2BepInExPack] System.TypeLoadException: Could not resolve type with token 01000031 (from typeref, class/assembly orig_OnDropletHitGroundServer, )
  at (wrapper managed-to-native) System.Reflection.MonoMethodInfo.get_method_info(intptr,System.Reflection.MonoMethodInfo&)
```

[InstanceBasedLoot.log](https://github.com/programit/RoR2InstanceLootPlugin/files/15425380/InstanceBasedLoot.log)
[InstanceBasedLootOnly.log](https://github.com/programit/RoR2InstanceLootPlugin/files/15425381/InstanceBasedLootOnly.log)

**Comment by nickg11** [comment]
A giant wall of text but the main take away is that the Artifact of Command code has been refactored so the references to it need to be adjusted. If you do decided to update the mod it would be greatly appreciated as I really enjoy running this mod with my friends ♥

**Comment by programit** [comment]
Thanks for the head up. I should be able to take a look this weekend. Based on above unless they did significant refactoring should be pretty straightforward to fix

**Comment by nickg11** [comment]
If it helps, KubeRoot updated his mod that interacts with the Artifact of Command. Here are the commits [Main Commit](https://gitlab.com/KubeRoot/ror2-commandqueue/-/commit/44975d21ef73f4a44b0337e3992dc30482197798) [Lib Update Commit](https://gitlab.com/KubeRoot/ror2-libs/-/commit/b5d33348ae3c3d4a744e0d714c2e15d1cd75fb14). He also mentioned that his issue was "It was indeed an issue with the game update, funnily enough the bug was caused solely by me assuming a certain field in the game cannot be accessed by mods - when it was switched from private to public, my reflection access stopped working, since it only specified NonPublic.". I hope this helps.

**Comment by programit** [comment]
Thanks Nick. Took a look and seems like they refactored their code a bit and the method I was hooking doesn't exist anymore. Fortunately the refactor wasn't huge and looks like they mostly moved the logic I was hooking to a new method inside PickupDropletController. I have a fix ready locally and will test tonight with a friend to make sure it all works as expected.

**Comment by programit** [comment]
PR #6 resolves this. Thanks for pointing it out!

**Comment by programit** [comment]
New version is now published. Let me know if you have any issues and thanks again!
