### ISSUE TITLE
Issue with the F3 command while using other mods. 

### ISSUE THREAD

**Issue by OakloreGaming** [programit/RoR2InstanceLootPlugin#7]
Hello! My friends and I have had a blast using this QOL loot share...it's just that after adding the RiskyStarterPack (made by Risky_Lives) mod to my list, I know have an issue where when I press F3 to grab my loot, it's dropping my health down to zero (though it still pulls items to me) and F2 brings the health back up, as well as toggling godmode. I can't figure out what mod in his pack is causing the issue. If it's easier, is there any way I can change the F3 shortcut to a different key? I'm sorry if this isn't a real issue, I just didn't know where else to ask.

**Comment by programit** [comment]
Hey! Awesome to hear others are enjoying the plugin as well. Assuming it's just two plugins overloading the same shortcut, it should be a pretty easy fix. Let me see if I can find time this weekend and make the shortcuts configurable.

**Comment by OakloreGaming** [comment]
Wow! Thanks for the speedy response! Looking forward to what you can muster up!

**Comment by OakloreGaming** [comment]
So after some uninstalling of different mods here and there from the RiskyStarterPack, we found the culprit of the F3 clash. Apparently TeammateRevival (by Moffein) was causing the problem. I'm not very savy with mods nor the console, so I wouldn't be surprised somewhere if I could remove their keybinding instead...now we don't HAVE to use that mod, but it was a pretty cool concept of healing your friends. I appreciate you if you're still going out of your way to make the shortcuts configurable! Thanks again.

**Comment by programit** [comment]
Good deal, I will still work to add ability to change the shortcuts, because inevitably there will be more mods in the future that also bind to the same key and cause issues so it's a good feature to have. Thanks for investigating!

**Comment by programit** [comment]
@OakloreGaming, I've pushed version 2.2.0 of the plugin just now, it adds a new command `instance_loot_hotkey`

Usage is like `instance_loot_hotkey F5` or `instance_loot_hotkey p`

Maybe one day I'll add a nicer UI for configuring, but for now through console, or the config settings in R2ModMan you can set the value. 

Let me know if you see any issues.

**Comment by OakloreGaming** [comment]
It's been working great! Thanks so much for this!
